apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-santa
  labels:
    app: santa-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: santa-app

  template:
    metadata:
      labels:
        app: santa-app
    spec:
      containers:
      - name: santa-container
        image: devopsproject1.azurecr.io/secretsanta:latest
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: servicesanta

spec:
  type: LoadBalancer
  selector:
    app: santa-app
  ports:
  - port: 80
    targetPort: 8080
